config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"

  post '/your_homepost_path', to: 'posts#index'
  
  resources :posts do
    member do
      post 'vote'
    end
  end

  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :shares, only: [:create, :destroy]

  resources :users, only: %i[new create] do
    member do
      get 'profile' # プロフィールページへのルーティングを追加
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :radio_name, :content, presence: true # radio_name, content は必須
  has_many :votes, dependent: :destroy # 投票は投稿が削除されたら一緒に削除
  has_many :shares # 投稿がシェアされたユーザー
  has_many :sharers, through: :shares, source: :user  # 投稿をシェアしたユーザーの一覧
  belongs_to :user, optional: true # 投稿はユーザーに紐づくが、ユーザーが削除されても投稿は残す
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy # ユーザーが削除されたら投稿も一緒に削除
  has_many :shares # ユーザーがシェアした投稿
  has_many :shared_posts, through: :shares, source: :post # ユーザーがシェアした投稿の一覧
  authenticates_with_sorcery! # sorcery で認証機能を使う
  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] } 
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] } 
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] } 
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
  
  def sharing?(post)
    shares.exists?(post_id: post.id)
  end
  def share(post)
    shares.create(post_id: post.id) unless sharing?(post)
  end

  def unshare(post)
    shares.find_by(post_id: post.id)&.destroy
  end

  def admin?
    self.admin
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote] 
  before_action :check_user, only: [:edit, :update, :destroy] 
  skip_before_action :require_login, only: [:index, :show, :create, :new, :vote] #ログインせず開けるページ

  def index
    @posts = Post.all  # 全ての投稿を取得
  end

  def new
    @post = Post.new
  end

  def create
    if logged_in?
      @post = current_user.posts.build(post_params) # ログインしているユーザーの投稿を作成
    else
      @post = Post.new(post_params) # ログインしていないユーザーも投稿を作成できる
    end
  
    if @post.save
      redirect_to @post # 保存が成功した場合、投稿詳細ページにリダイレクト
    else
      flash.now[:error] = '入力が不足しています' # 保存が失敗した場合、新規投稿ページ(topページ)を再表示
      render 'posts/new'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: '投稿が更新されました'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end

  def check_user
    unless @post.user_id == current_user&.id || current_user&.admin?
      Rails.logger.debug "Current user is not the owner of the post and not an admin."
      redirect_to root_path, alert: "You are not authorized to perform this action."
    else
      Rails.logger.debug "Current user is the owner of the post or an admin."
    end
  end

  def vote
    @post = Post.find(params[:id])
  
    if logged_in? # ログインしている場合
      if @post.votes.where(user_id: current_user.id).exists?
        # すでに投票済みの場合
        flash[:alert] = 'You have already voted for this post.'
      else
        # まだ投票していない場合
        @post.votes.create(user_id: current_user.id)
        flash[:notice] = 'Your vote was recorded.'
      end
    else # ログインしていない場合
      voted_posts = cookies[:voted_posts] ? JSON.parse(cookies[:voted_posts]) : []
  
      if voted_posts.include?(@post.id.to_s)
        # すでに投票済みの場合
        flash[:alert] = 'You have already voted for this post.'
      else
        # まだ投票していない場合
        @post.votes.create
        voted_posts << @post.id.to_s
        cookies[:voted_posts] = { value: JSON.generate(voted_posts), expires: 1.day.from_now }
        flash[:notice] = 'Your vote was recorded.'
      end
    end
  
    redirect_to post_path(@post, from: 'vote')
  end
  
  def show
    @post = Post.find(params[:id])
  end

  private

  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_path, alert: "The post you were looking for could not be found."
  end
  
  def check_user
    unless @post.user_id == current_user&.id || current_user&.admin?
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end
  
  def post_params
    params.require(:post).permit(:radio_name, :content) 
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    current_user.share(@post)
    redirect_to @post
  end

  def destroy
    @post = Share.find(params[:id]).post
    current_user.unshare(@post)
    redirect_to @post
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    skip_before_action :require_login, only: %i[top] #Topページはログイン不要（application_controller.rbで設定したbefore_actionをスキップする）
    def top 
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      if params[:remember_me]
        @user.remember_me!
        cookies.permanent.signed[:remember_me_token] = @user.remember_me_token
      end
      redirect_to profile_user_path(@user)
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create] #ログインせず開けるページ

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)  # ユーザーをログインさせる
      redirect_to profile_user_path(@user)
    else
      render :new
    end
  end

  def profile
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JN5QQR6QH3"></script>
<script>
window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JN5QQR6QH3');
</script>

app/views/posts/confirm_turbo.html.erb.erb
<h1>Confirm your post</h1>

<p>Radio Name: <%= @post.radio_name %></p>
<p>Content: <%= @post.content %></p>

<%= form_with(model: @post, url: posts_path, method: :post) do |form| %>
  <%= form.hidden_field :radio_name %>
  <%= form.hidden_field :content %>
  <%= form.submit "Confirm and Post" %>
<% end %>

app/views/posts/edit.html.erb
<h1 style="text-align: center; font-size: 2em; color: #333; font-handwriting">Edit</h1>
<div class="h-full w-full flex justify-center items-start px-4">

<%= form_with(model: @post, local: true) do |form| %>
  <div class="form-fields" style="display: flex; flex-direction: column; font-handwriting">
    <div class="field">
      <%= form.label :radio_name %>
      <%= form.text_field :radio_name, style: "width: 350px; height: 30px;" %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content, style: "width: 350px; height: 200px;" %>
    </div>

    <div class="actions" style="display: flex; justify-content: center;">
      <%= link_to 'キャンセル', posts_path, class: "btn btn-outline ml-4" %>
      <%= form.submit "編集完了", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/posts/index.html.erb
<h1 style="text-align: center; font-size: 2em; color: #333; font-handwriting">投稿一覧</h1>
<div class="h-full w-full flex justify-center items-start px-4 font-handwriting">
  <div class="h-96 w-full mt-14 carousel carousel-vertical rounded-box transform scale-400">
  <% @posts.order(created_at: :desc).each do |post| %>
    <div class="carousel-item h-full" style="background-color: rgba(246, 238, 201, 0.6); position: relative;">
      <div class="card w-full">
        <div class="card-body">
          <div style="display: flex; justify-content: space-between;">
            <div>
              <p style="font-size: 0.8em;">投稿日時: <%= post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
              <p style="font-size: 0.8em;">投票総数: <%= post.votes.count %></p>
            </div>
            <% if logged_in? && (current_user.id == post.user_id || current_user.email == 'home@Dayori') %>
              <div style="display: flex;">
            <%= link_to edit_post_path(post), style: "margin-right: 2px;" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="h-4 w-4 mr-2 inline-block" fill="currentColor">
                    <path d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.7 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160V416c0 53 43 96 96 96H352c53 0 96-43 96-96V320c0-17.7-14.3-32-32-32s-32 14.3-32 32v96c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h96c17.7 0 32-14.3 32-32s-14.3-32-32-32H96z"/>
                  </svg>
                <% end %>
                <%= form_with url: post_path(post), method: :delete, local: true do %>
                  <button type="submit" style="margin-left: 2px; background: none; border: none;">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="h-4 w-4 mr-2 inline-block" fill="currentColor">
                      <path d="M135.2 17.7C140.6 6.8 151.7 0 163.8 0H284.2c12.1 0 23.2 6.8 28.6 17.7L320 32h96c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 96 0 81.7 0 64S14.3 32 32 32h96l7.2-14.3zM32 128H416V448c0 35.3-28.7 64-64 64H96c-35.3 0-64-28.7-64-64V128zm96 64c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16z"/>
                    </svg>
                  </button>
                <% end %>
              </div>
            <% end %>
          </div>
          <hr style="border-width: 1.5px; border-color: #333;">
          <h2 class="card-title"><%= post.radio_name %></h2>
          <p style="font-size: 0.8em;"><%= post.content %></p>
        </div>
      </div>
      <%= button_to '投票する', vote_post_path(post), method: :post, class: "btn btn-primary", style: "position: absolute; right: 0; bottom: 0;" %>
    </div>
  <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1 style="text-align: center; font-size: 2em; color: #333; font-handwriting">新規投稿</h1>
<div class="h-full w-4/5 flex justify-end items-start font-handwriting">
<div class="h-96 w-full mt-14 carousel carousel-vertical rounded-box transform scale-400 font-handwriting">
<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>
<%= form_with model: @post || Post.new, url: posts_path, method: :post, id: 'post-form' do |form| %>
  <%= form.label :radio_name, "ラジオネーム" %>
  <div>
    <%= form.text_field :radio_name, maxlength: 25, placeholder: "名前", class: "input input-bordered input-accent w-full"  %>
  </div>
  <%= form.label :content, "本文" %>
  <div>
    <%= form.text_area :content, maxlength: 225, rows: 8, class: "textarea textarea-warning w-full", placeholder: "褒めpost" %>
  </div>
  <div class="w-full text-right">
    <% if current_user %>
      <%= form.submit "投稿", class: "btn btn-accent" %>
      <%= link_to '編集', edit_post_path(@post), class: "btn btn-accent" if @post&.persisted? %>
      <%= link_to '削除', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-accent" if @post&.persisted? %>
    <% else %>
      <button type="button" class="btn btn-accent" onclick="my_modal_5.showModal()">投稿</button>
    <% end %>
  </div>
<% end %>
  <!-- Daisy UIのモーダル -->
    <% unless current_user %>
    <dialog id="my_modal_5" class="modal modal-bottom sm:modal-middle">
      <div class="modal-box">
        <h3 class="font-bold text-lg">【注意】投稿内容の確認</h3>
        <p class="py-4">
          ゲストの場合、投稿内容の編集・削除ができません。<br>
          投稿内容に間違いがないか、<br>確認し「投稿を確定する」をクリックしてください。
        </p>
        <div class="modal-action">
        <button type="button" class="btn btn-error" onclick="document.getElementById('post-form').submit()">投稿を確定する</button>
          <button type="button" class="btn" onclick="my_modal_5.close()">編集する</button>
        </div>
      </div>
    </dialog>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div style="text-align: center; font-handwriting">
<img src="https://i.gyazo.com/a18a25c52becf065037838ef0f905ff3.png" alt="画像" style="display: block; margin: auto; width: 50%; font-handwriting">
<%= form_with model: @post || Post.new, url: posts_path, method: :post, id: 'post-form' do |form| %>
  <strong style="text-decoration: underline;"><%= form.label :radio_name, "ラジオネーム" %></strong>
  <div>
    <%= @post.radio_name %>
  </div>
  <strong style="text-decoration: underline;"><%= form.label :content, "本文" %></strong>
  <div>
    <%= @post.content %>
  </div>
  <% if params[:from] == 'vote' %>
    <strong style="text-decoration: underline;">
      <div>
      投票数: <%= @post.votes.count %>
      </div>
    </strong>
  <% end %>
  <div style="display: flex; justify-content: center;">
      <div class="twitter">
        <% share_text = params[:from] == 'vote' ? "【褒め便りへ投票しました】" : "【褒め便りへ投稿しました】" %>
        <% share_url = params[:from] == 'vote' ? post_url(@post) : root_url %>
        <%= link_to "https://x.com/intent/tweet?url=#{share_url}&text=#{share_text}%0a%0a", target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "シェア", class: "btn btn-primary", style: "display: inline-flex; align-items: center; justify-content: center; width: 120px; white-space: nowrap; flex-wrap: nowrap;" do %>
          <span>共有</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="margin-left: 10px; align-self: center;"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"/></svg>
        <% end %>
      </div>
      <% if @post&.persisted? %>
        <%= link_to '戻る', posts_path(@post), class: "btn btn-accent" if @post&.persisted? %>
      <% end %>
    </div>
</div>
<% end %>

app/views/shared/_before_login_header.html.erb
<header style="font-size: 25px;">
  <nav>
    <div class="navbar bg-base-100" style="background-color: #BBAB8C">
      <div class="flex-1">
        <%= link_to root_path, class: 'btn btn-ghost text-xl', style: 'font-size: 80px; height: 80px;' do %>
          <%= image_tag("https://i.gyazo.com/df33ce9bc34b954c21b7427ee42a8a6e.png", alt: "Logo", style: "height: 80px; vertical-align: middle;") %>
        <% end %>
      </div>
      <div class="flex-none">
        <ul class="menu menu-horizontal px-1" style="align-items: center;">
        <li><%= link_to 'ゲストユーザー', class: 'dropdown-item', style: 'font-size: 25px; padding: 5px;' %></li>
          <li>
            <%= link_to login_path, class: 'dropdown-item', style: 'font-size: 25px; padding: 5px;' do %>
              <%= image_tag("https://i.gyazo.com/9398355c50f4ed93fdff7e0373702c47.png", alt: "ログイン", style: "height: 50px; vertical-align: middle; padding: 5px;") %>
            <% end %>
          </li>
          <li>
            <details style="position: relative; z-index: 9999;">
            <summary style="font-size: 20px; padding: 5px;">
              <%= image_tag("https://i.gyazo.com/66b84def7036cafb9b2b105a22604763.png", style: 'height: 50px; vertical-align: middle;') %>
            </summary>
            <ul class="p-2 bg-base-100 rounded-t-none" style="width: 200%; white-space: nowrap; position: absolute; right: 0;">
              <li><%= link_to 'Top', root_path, style: 'font-size: 15px;' %></li>
              <li><%= link_to '新規投稿', new_post_path, style: 'font-size: 15px;' %></li>
              <li><%= link_to '投稿一覧', posts_path, style: 'font-size: 15px;' %></li>
            </ul>
          </details>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_header.html.erb
<header style="font-size: 25px;">
  <nav>
    <div class="navbar bg-base-100" style="background-color: #BBAB8C">
      <div class="flex-1">
        <%= link_to root_path, class: 'btn btn-ghost text-xl', style: 'font-size: 80px; height: 80px;' do %>
          <%= image_tag("https://i.gyazo.com/df33ce9bc34b954c21b7427ee42a8a6e.png", alt: "Logo", style: "height: 80px; vertical-align: middle;") %>
        <% end %>
      </div>
      <div class="flex-none">
        <ul class="menu menu-horizontal px-1" style="align-items: center;">
        <%= link_to "<strong>#{current_user.first_name}</strong>の<br>プロフィール".html_safe, profile_user_path(current_user), class: 'dropdown-item', style: 'font-size: 15px; line-height: 1.5; padding: 5px;' %>
          <li>
            <%= form_with url: logout_path, method: :delete, class: 'dropdown-item', style: 'padding: 0; margin: 0;' do %>
              <%= image_submit_tag("https://i.gyazo.com/0a6f083e5f557330a22fbdec248c447e.png", style: 'height: 40px; vertical-align: middle;') %>
            <% end %>
          </li>
          <li>
            <details style="position: relative; z-index: 9999;">
            <summary style="font-size: 20px; padding: 5px;">
              <%= image_tag("https://i.gyazo.com/66b84def7036cafb9b2b105a22604763.png", style: 'height: 50px; vertical-align: middle;') %>
            </summary>
            <ul class="p-2 bg-base-100 rounded-t-none" style="width: 200%; white-space: nowrap; position: absolute; right: 0;">
              <li><%= link_to 'Top', root_path, style: 'font-size: 15px;' %></li>
              <li><%= link_to '新規投稿', new_post_path, style: 'font-size: 15px;' %></li>
              <li><%= link_to '投稿一覧', posts_path, style: 'font-size: 15px;' %></li>
            </ul>
          </details>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shares/index.html.erb
<% if current_user.sharing?(@post) %>
  <%= form_for(current_user.shares.find_by(post_id: @post.id),
               method: :delete) do |f| %>
    <%= f.submit "Unshare", class: "btn" %>
  <% end %>
<% else %>
  <%= form_for(current_user.shares.build, url: shares_path) do |f| %>
    <div><%= hidden_field_tag :post_id, @post.id %></div>
    <%= f.submit "Share", class: "btn" %>
  <% end %>
<% end %>

app/views/static_pages/top.html.erb
<div class="hero min-h-screen" style="background-image: url(https://i.gyazo.com/13b49a8a4740c01fe65471cfdd5de9a7.png); font-handwriting">
  <div class="hero-overlay bg-opacity-0"></div>
  <div class="hero-content text-center text-neutral-content" style="color: #594545;">
    <div class="max-w-md">
    <h1 class="mb-5 text-4xl font-handwriting" style="margin-top: -60px;">褒め便り。</h1>
      <h5 class="mb-5 text-1xl font-handwriting">ラジオネーム、何にする？</h5>
      <p class="mb-5" style="font-size: 10px;">You're all doing a fantastic job! Mental health issues are real, and self-care is crucial. By affirming and being kind to yourself, you naturally become kinder to others. This is the essence of a kind world!</p>
      <%= link_to 'ゲストで投稿してみる', new_post_path, class: 'btn btn-accent', style: 'color: #black;' %>
      <%= link_to 'ログインして投稿', login_path, class: 'btn btn-accent', style: 'color: #black;' %>
      <br>
      <br>
      <br>
      <div class="animate-focus-in-expand font-handwriting" style="font-size: 14px;">
        <p>毎日お疲れさまです。</p>
        <p>何かと慌ただしい日々に、<br>毎日が 1週間が 1ヶ月...と過ぎていませんか？</p>
        <p>そんなあなたに、少しの癒しとエールを。</p>
        <p>褒め便り。でゆるっと１日を振り返ってみませんか？</p>
      </div>
      <br>
      <button class="btn" onclick="my_modal_5.showModal()">使い方</button>
    </div>
  </div>
  <!-- モーダルの定義 -->
  <dialog id="my_modal_5" class="modal modal-bottom sm:modal-middle font-handwriting">
    <div class="modal-box">
      <h3 class="font-handwriting text-lg">使い方</h3>
      <p class="py-4">
      <h1><strong><u>1. ラジオネームを決める</u><strong></h1>
      <h3>ラジオのように、匿名で気軽に投稿できます</h3>
      <h3>今日の気分で決めてみて下さい。</h3>
      <br>
      <h1><strong><u>2. 今日の褒め便りを投稿する</u><strong></h1>
      <h3>ラジオリスナーになった気分で、匿名で気軽に。<h3>
      <h3>テーマは「今日の自分を褒めるなら？」</h3>
      <br>
      <h3>１日を振り返って、自分を褒めてみましょう。</h3>
      <h3>小さなことでOK!その時の感情も一緒に書いてみて下さい。</h3>
      <br>
      <h1><strong><u>3. 他の人の褒め便りを見る</u><strong></h1>
      <h3>他の人の便りに共感したり、投票したりしてみましょう。</h3>
      <h3>あなたの送った褒め便りが、誰かの励みになるかもしれません。</h3>
      </p>
      <div class="modal-action">
        <form method="dialog">
          <button class="btn">Close</button>
        </form>
      </div>
    </div>
  </dialog>
</div>

app/views/user_sessions/new.html.erb
<h1 style="text-align: center; font-size: 2em; color: #333;">ログイン</h1>
<div class="container mx-auto flex items-start justify-center h-screen">
  <div class="row">
    <div class=" col-md-10 col-lg-8 mx-auto">
      <%= form_with url: login_path do |f| %>
        <div class="mb-3">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me, "ログイン状態を保持する" %>
        </div>
        <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
          <%= image_tag("https://i.gyazo.com/9398355c50f4ed93fdff7e0373702c47.png", alt: "Icon", style: "height: 20px;") %> ログイン
        <% end %>
      <% end %>
      <div class='text-center'>
        <%= link_to new_user_path, class: "btn btn-outline btn-accent" do %>
          <%= image_tag("https://i.gyazo.com/ac1e18e1c22d2ac80d8b787870bd5882.png", alt: "Icon", style: "height: 20px;") %> 新規登録
        <% end %>
        <%= link_to 'パスワードをお忘れの方はこちら', '#' %>
      </div>
    </div>
  </div>
</div>